import type { PrismaClient } from '@copo/db';
import type { AuditSink } from './audit';
import { AuthError } from './errors';
import type { Guard } from './authz/guard';
import { normaliseEmail } from './localProvider';
import { generateTemporaryPassword, hashPassword, validateNewPassword, verifyPassword } from './password';
import type { SessionService } from './sessions';

/**
 * Account administration (§2.1): administrator-created accounts, forced
 * first-login password change, administrator-initiated reset. There is
 * deliberately NO self-registration function in this package.
 *
 * Every administrative method authorises itself through the Guard
 * ('users.manage') — enforcement stays in one place even for account
 * management. changePassword is the one self-service operation and
 * authenticates by current password instead.
 */
export class AccountService {
  constructor(
    private readonly prisma: PrismaClient,
    private readonly guard: Guard,
    private readonly sessions: SessionService,
    private readonly audit: AuditSink,
  ) {}

  /**
   * Administrator creates an account. Returns the temporary password
   * exactly once, for out-of-band handover; the user must change it at
   * first login. The internal id is generated by the database and is
   * never the email (§2.1).
   */
  async createUser(
    actorId: string,
    args: { email: string; fullName: string },
  ): Promise<{ userId: string; temporaryPassword: string }> {
    await this.guard.require(actorId, { type: 'users.manage' });

    const email = normaliseEmail(args.email);
    const temporaryPassword = generateTemporaryPassword();
    const user = await this.prisma.user.create({
      data: {
        email,
        fullName: args.fullName,
        identityProvider: 'LOCAL',
        passwordHash: await hashPassword(temporaryPassword),
        mustChangePassword: true,
        isActive: true,
      },
    });

    await this.audit.record({
      action: 'USER_CREATED',
      actorId,
      entityType: 'User',
      entityId: user.id,
      after: { email, fullName: args.fullName, identityProvider: 'LOCAL' },
    });

    return { userId: user.id, temporaryPassword };
  }

  /**
   * Administrator-initiated reset: issues a new temporary password,
   * forces a change at next login, and logs the user out everywhere.
   */
  async resetPassword(actorId: string, userId: string): Promise<{ temporaryPassword: string }> {
    await this.guard.require(actorId, { type: 'users.manage' });

    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) throw new AuthError('INVALID_CREDENTIALS', 'No such user');
    if (user.identityProvider !== 'LOCAL') {
      throw new AuthError('WRONG_PROVIDER', 'Password reset applies to local accounts only');
    }

    const temporaryPassword = generateTemporaryPassword();
    await this.prisma.user.update({
      where: { id: userId },
      data: { passwordHash: await hashPassword(temporaryPassword), mustChangePassword: true },
    });
    await this.sessions.revokeAllForUser(userId);

    await this.audit.record({ action: 'PASSWORD_RESET', actorId, entityType: 'User', entityId: userId });
    return { temporaryPassword };
  }

  /**
   * Self-service password change — the forced first-login change and any
   * later voluntary change. Verifies the current password, applies the
   * policy, clears mustChangePassword, and revokes EVERY session
   * (including the one performing the change — the app issues a fresh
   * session immediately after, so a stolen cookie dies here too).
   */
  async changePassword(userId: string, args: { currentPassword: string; newPassword: string }): Promise<void> {
    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user || !user.isActive) throw new AuthError('INVALID_CREDENTIALS', 'Account unavailable');
    if (user.identityProvider !== 'LOCAL' || user.passwordHash === null) {
      throw new AuthError('WRONG_PROVIDER', 'Passwords are managed by the identity provider');
    }
    if (!(await verifyPassword(user.passwordHash, args.currentPassword))) {
      throw new AuthError('INVALID_CREDENTIALS', 'Current password is incorrect');
    }

    const problems = validateNewPassword(args.newPassword, { email: user.email });
    if (args.newPassword === args.currentPassword) problems.push('must differ from the current password');
    if (problems.length > 0) {
      throw new AuthError('PASSWORD_POLICY', `New password ${problems.join('; ')}`);
    }

    await this.prisma.user.update({
      where: { id: userId },
      data: { passwordHash: await hashPassword(args.newPassword), mustChangePassword: false },
    });

    await this.sessions.revokeAllForUser(userId);
    await this.audit.record({ action: 'PASSWORD_CHANGED', actorId: userId, entityType: 'User', entityId: userId });
  }

  async deactivateUser(actorId: string, userId: string): Promise<void> {
    await this.guard.require(actorId, { type: 'users.manage' });
    await this.prisma.user.update({ where: { id: userId }, data: { isActive: false } });
    await this.sessions.revokeAllForUser(userId);
    await this.audit.record({ action: 'USER_DEACTIVATED', actorId, entityType: 'User', entityId: userId });
  }

  async reactivateUser(actorId: string, userId: string): Promise<void> {
    await this.guard.require(actorId, { type: 'users.manage' });
    await this.prisma.user.update({ where: { id: userId }, data: { isActive: true } });
    await this.audit.record({ action: 'USER_REACTIVATED', actorId, entityType: 'User', entityId: userId });
  }
}
